server:
  port: 8081
  
spring:
  cloud:
    services:
      registrationMethod: route

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
    
---

server:
  context-path: /metrics
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQL5Dialect
---

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
---
eureka:
  instance:
    non-secure-port: 80
    hostname: ${vcap.application.uris[0]:localhost:8761}
  
  client:
    service-url:
      defaultZone: ${vcap.services.eureka-cb.credentials.url:http://localhost:8761/eureka/}
---
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false      
---
management:
  security:
    enabled: false
---
endpoints:
  env:
    enabled: false

    