server:
  port: 8081
  
spring:
  cloud:
    services:
      registrationMethod: route

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
    
---
spring:
  profiles: local-mssql
  datasource:
    url: jdbc:mysql://localhost:3306/amitdb?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      
---
spring:
  profiles:
    active: local-mssql