server:
  port: 8081
  
spring:
  cloud:
    services:
      registrationMethod: route

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
    
---
spring:
  profiles: local-mssql
  datasource:
    url: jdbc:mysql://localhost:3306/amitdb?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
---
server:
  context-path: /metrics
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQL5Dialect
---
spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/amitdb?useSSL=false
---
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
---
eureka:
  instance:
    non-secure-port: 80
    hostname: ${vcap.application.uris[0]:localhost:8761}
  
  client:
    service-url:
      defaultZone: ${vcap.services.eureka-cb.credentials.url:http://localhost:8761/eureka/}
---
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false      
      